// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// comp_form
arma::mat comp_form(arma::mat B);
RcppExport SEXP _VARMA_comp_form(SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_form(B));
    return rcpp_result_gen;
END_RCPP
}
// stack_obs
arma:: mat stack_obs(arma::mat nn, arma::uword p, arma::uword r);
RcppExport SEXP _VARMA_stack_obs(SEXP nnSEXP, SEXP pSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(stack_obs(nn, p, r));
    return rcpp_result_gen;
END_RCPP
}
// advance_vec
arma::vec advance_vec(arma::vec e, arma::vec E);
RcppExport SEXP _VARMA_advance_vec(SEXP eSEXP, SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(advance_vec(e, E));
    return rcpp_result_gen;
END_RCPP
}
// long_run_var
arma::mat long_run_var(arma::sp_mat A, arma::sp_mat Q, arma::uword m, arma::uword p);
RcppExport SEXP _VARMA_long_run_var(SEXP ASEXP, SEXP QSEXP, SEXP mSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(long_run_var(A, Q, m, p));
    return rcpp_result_gen;
END_RCPP
}
// VARMA_MSE
Rcpp::List VARMA_MSE(arma::mat B, arma::mat Q, arma::mat Y);
RcppExport SEXP _VARMA_VARMA_MSE(SEXP BSEXP, SEXP QSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(VARMA_MSE(B, Q, Y));
    return rcpp_result_gen;
END_RCPP
}
// Kfilter
Rcpp::List Kfilter(arma::mat Y, arma::mat B, arma::mat q, arma::mat H, arma::vec R);
RcppExport SEXP _VARMA_Kfilter(SEXP YSEXP, SEXP BSEXP, SEXP qSEXP, SEXP HSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(Kfilter(Y, B, q, H, R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VARMA_comp_form", (DL_FUNC) &_VARMA_comp_form, 1},
    {"_VARMA_stack_obs", (DL_FUNC) &_VARMA_stack_obs, 3},
    {"_VARMA_advance_vec", (DL_FUNC) &_VARMA_advance_vec, 2},
    {"_VARMA_long_run_var", (DL_FUNC) &_VARMA_long_run_var, 4},
    {"_VARMA_VARMA_MSE", (DL_FUNC) &_VARMA_VARMA_MSE, 3},
    {"_VARMA_Kfilter", (DL_FUNC) &_VARMA_Kfilter, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_VARMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
