# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnrm <- function(n, mu, Sigma) {
    .Call('_VARMA_mvrnrm', PACKAGE = 'VARMA', n, mu, Sigma)
}

rinvwish <- function(n, v, S) {
    .Call('_VARMA_rinvwish', PACKAGE = 'VARMA', n, v, S)
}

invchisq <- function(nu, scale) {
    .Call('_VARMA_invchisq', PACKAGE = 'VARMA', nu, scale)
}

BReg <- function(X, Y, Int, Bp, lam, nu, reps = 1000L, burn = 1000L) {
    .Call('_VARMA_BReg', PACKAGE = 'VARMA', X, Y, Int, Bp, lam, nu, reps, burn)
}

BReg_diag <- function(X, Y, Int, Bp, lam, nu, reps = 1000L, burn = 1000L) {
    .Call('_VARMA_BReg_diag', PACKAGE = 'VARMA', X, Y, Int, Bp, lam, nu, reps, burn)
}

comp_form <- function(B) {
    .Call('_VARMA_comp_form', PACKAGE = 'VARMA', B)
}

stack_obs <- function(nn, p, r = 0L) {
    .Call('_VARMA_stack_obs', PACKAGE = 'VARMA', nn, p, r)
}

advance_vec <- function(e, E) {
    .Call('_VARMA_advance_vec', PACKAGE = 'VARMA', e, E)
}

VARMA_MSE <- function(B, Q, Y) {
    .Call('_VARMA_VARMA_MSE', PACKAGE = 'VARMA', B, Q, Y)
}

KLike <- function(B, q, H, R, Y) {
    .Call('_VARMA_KLike', PACKAGE = 'VARMA', B, q, H, R, Y)
}

DKsmooth <- function(B, q, H, R, Y) {
    .Call('_VARMA_DKsmooth', PACKAGE = 'VARMA', B, q, H, R, Y)
}

DKsmoothMF <- function(B, q, H, R, Y, W) {
    .Call('_VARMA_DKsmoothMF', PACKAGE = 'VARMA', B, q, H, R, Y, W)
}

