# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comp_form <- function(B) {
    .Call('_VARMA_comp_form', PACKAGE = 'VARMA', B)
}

stack_obs <- function(nn, p, r = 0L) {
    .Call('_VARMA_stack_obs', PACKAGE = 'VARMA', nn, p, r)
}

advance_vec <- function(e, E) {
    .Call('_VARMA_advance_vec', PACKAGE = 'VARMA', e, E)
}

VARMA_MSE <- function(B, Q, Y) {
    .Call('_VARMA_VARMA_MSE', PACKAGE = 'VARMA', B, Q, Y)
}

KLike <- function(B, q, H, R, Y) {
    .Call('_VARMA_KLike', PACKAGE = 'VARMA', B, q, H, R, Y)
}

DKsmooth <- function(B, q, H, R, Y) {
    .Call('_VARMA_DKsmooth', PACKAGE = 'VARMA', B, q, H, R, Y)
}

DKsmoothMF <- function(B, q, H, R, Y, W) {
    .Call('_VARMA_DKsmoothMF', PACKAGE = 'VARMA', B, q, H, R, Y, W)
}

