# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comp_form <- function(B) {
    .Call('_VARMA_comp_form', PACKAGE = 'VARMA', B)
}

stack_obs <- function(nn, p, r = 0L) {
    .Call('_VARMA_stack_obs', PACKAGE = 'VARMA', nn, p, r)
}

advance_vec <- function(e, E) {
    .Call('_VARMA_advance_vec', PACKAGE = 'VARMA', e, E)
}

long_run_var <- function(A, Q, m, p) {
    .Call('_VARMA_long_run_var', PACKAGE = 'VARMA', A, Q, m, p)
}

VARMA_MSE <- function(B, Q, Y) {
    .Call('_VARMA_VARMA_MSE', PACKAGE = 'VARMA', B, Q, Y)
}

Kfilter <- function(Y, B, q, H, R) {
    .Call('_VARMA_Kfilter', PACKAGE = 'VARMA', Y, B, q, H, R)
}

